version: '3.8'
services:
  medical-engine:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - WHATSAPP_VERIFY_TOKEN=honeybee_secure_token_2026
      - WHATSAPP_APP_SECRET=20e3f4b18feb5f178ed0613ab56f2cb1
      - GROQ_API_KEY=your_groq_key_here
      - WHATSAPP_TOKEN=your_whatsapp_token_here
      - PHONE_NUMBER_ID=1265844336620784